### ISSUE TITLE
Add support for OpenAPI v3.0 `style` serialization method

### ISSUE THREAD

**Issue by ericabouaf** [ferdikoomen/openapi-typescript-codegen#772] opened 2021-07-01 10:03 UTC
OpenAPI v3.0 supports several serializations options through the `style` and `explode` parameters.

We use both in our API definition, which are correctly handled by the swagger-js client, but not this code generator yet.
The generator currently only supports the `form` value of `style` (which is the default).

We would like to use the `deepObject` serialization method.
Regarding `spaceDelimited` and `pipeDelimited`, they do not seem to be implemented either, but are similar to OpenAPI v2 collectionFormat: ssv and collectionFormat: pipes which are already implemented.

Open Api reference: https://swagger.io/docs/specification/serialization/

Related to https://github.com/ferdikoomen/openapi-typescript-codegen/issues/654, and maybe to https://github.com/ferdikoomen/openapi-typescript-codegen/issues/658

**Comment by ferdikoomen** [comment] 2021-11-11 15:08
Closing this one as duplicate of: https://github.com/ferdikoomen/openapi-typescript-codegen/issues/654
Lets continue there

**Closed by ferdikoomen** 2021-11-11 15:08 UTC
