### ISSUE TITLE
Describing an expected use case of the library 

### ISSUE THREAD

**Issue by mvasin** [ferdikoomen/openapi-typescript-codegen#453] opened 2020-11-28 16:21 UTC
The OpenAPI is the specification that "defines a standard, language-agnostic interface to RESTful APIs" (quoting the spec itself). So we're supposed to deal with RESTful APIs, not just an API that uses HTTP as a transport.

[According to the author](https://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven) of the REST as a concept,

> A REST API should never have “typed” resources that are significant to the client. Specification authors may use resource types for describing server implementation behind the interface, but those types must be irrelevant and invisible to the client. The only types that are significant to a client are the current representation’s media type and standardized relation names.

That means if we're dealing with truly RESTful APIs, we shouldn't care about the types. Why would we generate the types using this package then? Should we make a disclaimer that, ideally, one wouldn't need this library, and describe the use case(s) when he/she would need it?

To give some context: we've got the generation step brought into a project a while ago, and now as I'm digging into the project, I doubt that we need the generation step. We've got a simple CRUD app a-la books & authors.

But I also can miss some obvious things, so I want to share my concerns and get some feedback.

**Comment by ferdikoomen** [comment] 2020-11-30 20:45
@mvasin Yes, Roy Fielding has a good point: When designing and building 'true' REST(ful) API's we should not care about 'types'. Instead it's all about defining logical routes (resource identifiers), using standards that are already there (GET/PUT/POST/DELETE in case of a HTTP endpoint), creating something that is completely stateless and has stuff like hateoas links to define relationships in your data. A end consumer of the REST API should indeed not care about types. 

However, when your REST API sends data to a consumer, then it will send this data in a certain format, lets say we request a user from the system:

**/get/user/1**
```json
{
   "name": "John",
   "age": 36
}
```
If you are designing a consistent stateless REST API, then this return format should stay very similar. Otherwise the REST API will be very hard to consume. The same is true for the resource identifiers: to get a user from your system you will define a path like **/get/user/{id}**, again this path should stay the same and it should (by design) return the same type of data. 
So, we already have 'designed' return formats and 'designed' paths. You could call this Models and Services... But the REST protocol does not provide a way for us to describe these formats. Sure, we can document them and provide a PDF, but there is no nice standard to do so. This is where OpenAPI comes in.

OpenAPI allows you to document your RESTful API's, so for a consumers it's clear what the resource identifiers are, how they should be called and what the return data would be. You can even get a nice UI so developers can play around with the REST API. And the documentation follows a specification that can be tested and checked. Keep in mind: The fact that you can create a OpenAPI spec, does not mean your REST API is 'correct' in terms of what Roy Fielding is describing in his article, it just means you have documented _an_ API that works semi RESTful ;-)

OpenAPI also does not describe HOW we should convert this spec to a client. You could (in theory) just call the REST API using a standard fetch client and don't care about the return format (just guess the output like if you where writing Javascript). But the fact it, there is a return format and we can describe it, so why don't we use it :-) In my opinion Roy Fielding is not describing that we can never use Models, he just does not a direct 1:1 relationship between the REST API format and some internal model. This is a thing i also see happening a lot, where the OpenAPI return types are direct mapping of a .Net or Java model (that might not be the best fit). And if we look at other (older) API formats like SOAP with WSDL, then there is a much more tight coupling between language/API and consumer.

Anyhow, if you are using a very simple REST api, then maybe you don't need this library. In my current project we have an API with 30+ endpoints and a ton of different return formats, so it's easy to loose track... this is where OpenAPI and some sugar syntax models can help the team (that is the end goal for all of this).

**Comment by mvasin** [comment] 2020-12-01 12:59
Thank you for the detailed answer, Ferdi!

The text below is a bit verbose because it's thinking out loud. But hopefully you will distill the point :)

First, on URLs. Roy Fielding says in the article:

> A REST API must not define fixed resource names or hierarchies (an obvious coupling of client and server). Servers must have the freedom to control their own namespace. Instead, allow servers to instruct clients on how to construct appropriate URIs.

This seems to be the complete opposite of what OpenAPI aims for.

Ray goes on with

> Failure here implies that clients are assuming a resource structure due to out-of-band information.

Where in our case the out-of-band information he is referring to is the `/paths` property in the spec. As far as I can tell Roy's advice is to provide a single API entry point and to have the rest of the paths communicated to the client in-band (within server responses).

To machine-reason about those links, some metadata must provided along with the links, and both the server and the client must agree on the metadata meaning "out-of-band" and implement algorithms correspondingly. To communicate that the server and the client are speaking the same protocol (the agreed-upon logic how to process metadata can be applied), a custom media type (HTTP header) should used - `Content-Type: application/vnd.myCompany.myApp+json` instead of `Content-Type: application/json`.

If I work on a CRUD app that manipulates books, authors and genres, I need to agree with the server upfront about the notion of books, authors and genres. In all the practical cases I've seen, such an agreement is using OpenAPI and hardcoding the corresponding `/books`, `/authors` and `/genres` API URLs into the frontend codebase. But if, for instance, the server and the client would agree on the notion of "items" (= author, book) and "tags" (= genre) instead, the server would be able to introduce a new `/languages` endpoint as a HATEOAS link (in pseudocode, `link to=/languages rel=tag`), and the client will be ready to process that without code changes. I think that's the flexibility Roy is aiming for.

Now, to the data shape. If a book has one data shape today and slightly different tomorrow, as a UI dev I may or may not care - for instance, I can just loop over the OpenAPI spec fields and render them in a form according to their type (enum, number, string), and also apply OpenAPI validation. In that case, I don't need the library - the hardcoded interfaces would stand in the way (I'd rather use the spec directly and grab the OpenAPI spec types and/or a validation library). If displaying all the fields as is from the server won't suit me, there's a middle ground - I can mix-in some "middleware" that would throw away some fields, re-order fields, "show only these specific known fields and ignore newly added", etc - any logic. I did that in a project.

At the same time, like with your user example, while some fields are for purely for presentational purposes and are not critical, others have rigid requirements, maybe from a third system (let's imagine a separate authorisation or payments backend). Just like with the paths, the choice is either to hardcode the fields (to expect specifically `userId` property in the path response) or to add some metadata in the OpenAPI spec.

```
  /users:
    parameters:
      - in: path
        name: userId
        description: The id of the user
        schema:
          type: integer
       metaType: userId
      - in: path
        name: firstName
        description: The first name of the user
        schema:
          type: string
       metaType: other
```

If I will hardcode the `metaType` instead of `name`, that will allow me to treat `metaType=other` differently, i.e. automatically show new fields when server provides them.

> You could (in theory) just call the REST API using a standard fetch client and don't care about the return format (just guess the output like if you where writing Javascript). But the fact it, there is a return format and we can describe it, so why don't we use it :-)

My dilemma is not between describing or guessing TypeScript interfaces, it is between turning an OpenAPI endpoint response data shape into a TypeScript interface and baking into the code, or staying flexible by reading the OpenAPI  spec at run-rime and generating form fields / table columns dynamically.

Thinking if the spec be the part of the API response (in-band) or not, one thing popped up in my head: what if we treat the OpenAPI document as _the_ single API entrypoint Roy was suggesting, the part of the API? Then the only question for the backend and the frontend would be how to agree on meaningful metadata for paths and fields. But that would stresses that we shouldn't turn OpenAPI into hardcoded types.

Instead of hardcoding the specific endpoint response field names, some metadata that can be associated with those fields can be hardcoded instead. That would give an extra flexibility, at the price of extra inderection.

And now we're getting to the resolution of the issue. Here's a scratch:

If you can create the UI from the OpenAPI document, using this library (generating the types baking them at build-time) will make the code less flexible. If there are endpoint response properties that are tangled with business logic, either add extra metadata next to those properties in the OpenAPI spec and hardcode the metadata instead of the field names (think of roles of the fields, the semantics of the fields, instead of the literal field names, although often they will be the same). In case when the most of response properties are uniquely tangled with the business logic and adding metadata (grouping into roles) won't add much but redundant inderection, feel free to use the lib - generate the TypeScript interfaces and rely on them in the code.

**Comment by ferdikoomen** [comment] 2021-09-27 19:09
@mvasin closing this thread because its a very different architecture then intended with this (more static) client generator

**Closed by ferdikoomen** 2021-09-27 19:09 UTC
Labels: question
