### ISSUE TITLE
Unable to recognize the "openAPI" entry as the name of a Cmdlet, function, script file, or executable program. Please check the spelling of the name, if it includes Path, please make sure the path is correct and try again.

### ISSUE THREAD

**Issue by Zixueban** [ferdikoomen/openapi-typescript-codegen#2059] opened 2024-03-08 13:06 UTC
When I execute the command openAPI -- input http://localhost:7529/api/v3/api -Docs -- output/ Generated -- client axes, the following error will appear
![image](https://github.com/ferdikoomen/openapi-typescript-codegen/assets/153580934/57049cee-170c-4cd3-9d36-ac5aa2293dbe)

**Comment by mrlubos** [comment] 2024-03-08 13:20
@Zixueban is this a duplicate of https://github.com/ferdikoomen/openapi-typescript-codegen/issues/2010?

**Comment by Zixueban** [comment] 2024-03-09 02:50
> @Zixueban is this a duplicate of #2010?

Thank you very much. The issue has been resolved

**Comment by mrlubos** [comment] 2024-03-09 03:41
@Zixueban why was it failing for you? Can you share which package it was conflicting with?

**Comment by Zixueban** [comment] 2024-03-10 05:40
@mrlubos I'm not sure, the previous usage was fine, but after a while, inexplicably, the problem arose. I tried the method provided in # 2010 and it was resolved

**Comment by mrlubos** [comment] 2024-03-10 05:54
@Zixueban great! I plan to fix this properly in [@nicolas-chaulet/openapi-typescript-codegen](https://github.com/nicolas-chaulet/openapi-typescript-codegen), can I ping you once it's fixed to give it a try?

**Comment by Zixueban** [comment] 2024-03-11 12:19
@mrlubos great！Thank you very much

**Comment by mrlubos** [comment] 2024-03-17 04:44
@Zixueban this is fixed in [v0.27.29](https://www.npmjs.com/package/@nicolas-chaulet/openapi-typescript-codegen/v/0.27.29) 🎉 

Please use `openapi-ts` moving forward!

**Closed** 2024-03-19 07:30 UTC
